target: is_recid

features:
  numerical:
    - age
    - juv_fel_count
    - juv_misd_count
    - juv_other_count
    - priors_count
    - jailtime
  
  categorical:
    - sex
    - race
    - c_charge_degree
    
  binary: []
  dates: []
  ordinal: []
  
  exclude: []

preprocessing:
  sample_size: 1000
  
  missing_value_codes: {}
  
  # Feature engineering
  standardise_numerical: true
  one_hot_categoricals: true
  
  # Train/test split
  test_size: 0.2
  random_state: 42
